version: '3.8'

services:
  squid:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "3128:3128"
    volumes:
      - ./squid-lab/squid.conf:/etc/squid/squid.conf
      - ./squid-lab/cache:/var/spool/squid
    depends_on:
      - aspnet-app
    networks:
      - app-network
    restart: unless-stopped
    


  nginx:
    build:
      context: ./nginx # Ruta a la carpeta de Nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Nginx escuchará en el puerto 80 del host
    depends_on:
      - aspnet-app # Nginx dependerá de que tu app ASP.NET Core esté levantada
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx_logs:/var/cache/nginx # Volumen persistente para la caché de Nginx
    # Puedes mapear los logs de Nginx también si quieres verlos fácilmente
    # - ./nginx_logs:/var/log/nginx
    networks:
      - app-network

  aspnet-app:
    build:
      context: ./aspnet-app
      dockerfile: Dockerfile
    container_name: aspnet-cache-app
    ports:
      - "8080:8080" # Puedes exponerlo si quieres acceder directamente a la app, si no, puedes quitarlo
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./aspnet-app/data:/app/data # persistencia de la base de datos SQLite
    networks:
      - app-network

  varnish:
    image: varnish:6.0 # O una versión más reciente si está disponible
    container_name: varnish-cache
    ports:
      - "800:80" # Puerto público para acceder a Varnish
      - "6082:6082" # Puerto de administración de Varnish (VCL, stats)
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    depends_on:
      - aspnet-app
    command: ["varnishd", "-F", "-a", ":80", "-s", "malloc,256m", "-f",
     "/etc/varnish/default.vcl", "-T", ":6082","-p" ,"http_req_hdr_len=2048",
     "-p","http_req_size=10240"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
